[database]
path = ./brbgp.db

[server]
host = 0.0.0.0
port = 8000

[notifications]
telegram_enabled = false
telegram_bot_token = 
telegram_chat_id = 
whatsapp_enabled = false
webhook_enabled = false
webhook_url = 

[cloudflare]
api_token = iwMWTPcP2YGL4e6egPw0wLOY6u5r77hpuUwR4DRl
account_id = 2a6773f1533fad3e493a704ab182a355

[ollama]
enabled = true
base_url = http://10.1.254.32:11434
model = llama3

[bgp]
collectors = ripe-ris,ixbr
update_interval = 300
